var solution = require('./solution.js');
// solution.one();
// solution.two();
// solution.three();
// solution.four();
// solution.five();
// solution.six();
// solution.seven();
// solution.eight();
// solution.nine();
// solution.ten();
// solution.eleven();
// solution.twelve();
// solution.thirteen();
